

start C:\Users\student\Desktop\지훈\work_db;

--1
SELECT *FROM TAB;

--2
DESC BONUS;
DESC DEPT;
DESC EMP;
DESC SALGRADE;

--3
SELECT *FROM EMP;

--4
SELECT EMPNO,ENAME,SAL FROM EMP;

--5
SELECT DISTINCT SAL FROM EMP ;

--6
SELECT ENAME AS "이 름",SAL AS "월 급" FROM EMP;

--7
SELECT ENAME,SAL,SAL+COMM AS 실급여 FROM EMP WHERE COMM IS NOT NULL;

--8
SELECT EMPNO,ENAME,SAL FROM EMP WHERE ENAME ='SCOTT';

--9
SELECT EMPNO,ENAME,JOB FROM EMP WHERE JOB ='SALESMAN';

--10
SELECT EMPNO,ENAME,SAL FROM EMP WHERE EMPNO = 7499 or EMPNO = 7521 or EMPNO = 7654;

--11
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL >=1500 AND SAL <=3000;

--12
SELECT ENAME FROM EMP WHERE DEPTNO IS NULL;

--13
SELECT *FROM EMP ORDER BY SAL DESC; 